import builtins from 'builtin-modules';
import child_process from 'child_process';
import esbuild from 'esbuild';
import fs from 'fs';
import process from 'process';

const prod = process.argv.includes('production')

let runScriptPlugin = {
	name: 'run-script',
	setup(build) {
		build.onEnd(result => {
			if (result.errors.length > 0) {
				return
			}
			const scriptName = 'sync-plugin.sh'
			if (!fs.existsSync(scriptName)) {
				return
			}
			console.log(`run ${scriptName}`);
			child_process.exec(`bash ${scriptName}`, (err, stdout, stderr) => {
				if (err) {
					console.error(`run ${scriptName} error:`, err, stdout, stderr)
				}
			})
		})
	},
}

const buildOptions = {
	banner: {
		js: '/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */',
	},
	define: {
		'process.env.BUILD_ENV': JSON.stringify(prod ? 'production' : 'development'),
	},
	entryPoints: ['src/main.ts', 'src/styles.css'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		...builtins],
	format: 'cjs',
	target: 'es2016',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outdir: 'build',
	legalComments: 'inline',
	plugins: [runScriptPlugin],
};

if (prod) {
	esbuild.build(buildOptions).catch(() => process.exit(1));
} else {
	esbuild.context(buildOptions).then(ctx => {
		ctx.watch();
		console.log('Watching for changes...');
	});
}
